Revert "adb: add transport benchmark."
This reverts commit 8c7f0df3c2e56ca3733fbf4495081001f0c40cb2.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293